language: csharp
dotnet: 2.1.301
mono: none

matrix:
  include:
    - os: osx
    - os: linux
      addons:
        apt:
          packages:
            - libiomp5

script:
  - export OMP_NUM_THREADS=4
  - dotnet build QsharpLibraries.sln
  - dotnet test Samples/UnitTesting
  - travis_wait 30 dotnet test LibraryTests
