#
# Build configuration file to run build on azure-pipelines
#
name: $(Build.Major).$(Build.Minor).$(BuildId)

trigger:
- main

pr:
- main
- feature/*

schedules:
- cron: "0 9 * * Sat"
  displayName: 'Build for Component Governance'
  branches:
    include:
    - main
  always: true

variables:
  Build.Major: 1
  Build.Minor: 0
  Build.Patch: $(Build.BuildId)
  Build.Configuration: 'Release'
  Drops.Dir: $(Build.ArtifactStagingDirectory)/drops
  IQSharp.Hosting.Env: 'build-agent-quantum'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: Build/steps.yml

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    inputs:
      failOnAlert: true

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: Build/steps.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: Build/steps.yml
