#
# Build configuration file to run build on azure-pipelines
#
name: $(Build.Major).$(Build.Minor).$(BuildId)
trigger:
- master

variables:
  Build.Major: 1
  Build.Minor: 0
  Build.Patch: $(Build.BuildId)
  Build.Configuration: 'Release'
  Drops.Dir: $(Build.ArtifactStagingDirectory)/drops

jobs:
- job: Windows
  pool: 'Hosted VS2017'
  steps:
  - template: Build/steps.yml
- job: macOS
  pool: 'Hosted macOS'
  steps:
  - template: Build/steps.yml
- job: Linux
  pool: 'Hosted Ubuntu 1604'
  steps:
  - template: Build/steps.yml
