// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Microsoft.Extensions.Logging;
using Microsoft.Quantum.Chemistry;
using System.Linq;
using Microsoft.Quantum.Chemistry.OrbitalIntegrals;

// This loads a Hamiltonian from file and computes some of its features
// - L1-Norm of terms

namespace Microsoft.Quantum.Chemistry.Sample
{

    class Program
    {

        static void Main(string[] args)
        {
            var logger = Logging.LoggerFactory.CreateLogger<Program>();

            // Directory containing integral data generated by Microsoft.
            //Example Liquid data format files
            /*
            "h2_sto3g_4.dat" // 4 SO
            "B_sto6g.dat" // 10 SO
            "Be_sto6g_10.dat" // 10 SO
            "h2o_sto6g_14.dat" // 14 SO
            "h2s_sto6g_22.dat" // 22 SO
            "co2_sto3g_30.dat" // 30 SO
            "co2_p321_54.dat" // 54 SO
            "fe2s2_sto3g.dat" // 110 SO
            "nitrogenase_tzvp_54.dat" // 108 SO
            */

            string LiquidRoot = @"..\IntegralData\Liquid\";
            string LiquidFilename = "Be_sto6g_10.dat";

            // For loading data in the format consumed by Liquid.
            logger.LogInformation($"Processing {LiquidFilename}");
            var generalHamiltonian0 = LiQuiD.Deserialize($@"{LiquidRoot}\{LiquidFilename}").Single()
                .OrbitalIntegralHamiltonian
                .ToFermionHamiltonian(IndexConvention.UpDown);

            // For loading data in the YAML format.
            string YAMLRoot = @"..\IntegralData\YAML\";
            string YAMLFilename = "lih_sto-3g_0.800_int.yaml";
            var generalHamiltonian1 = Broombridge.Deserializers.DeserializeBroombridge($@"{YAMLRoot}\{YAMLFilename}")
                .ProblemDescriptions.Single()
                .OrbitalIntegralHamiltonian
                .ToFermionHamiltonian(IndexConvention.UpDown);
            // Read Hamiltonian terms from file.

            logger.LogInformation("End read file. Computing one-norms.");
            foreach (var termType in generalHamiltonian0.Terms.Keys)
            {
                var line = $"One-norm for term type {termType}: {generalHamiltonian0.Norm(new[] { termType }, 1.0)}";
                logger.LogInformation(line);
            }
            logger.LogInformation("Computed one-norm.");

            if (System.Diagnostics.Debugger.IsAttached)
            {
                System.Console.ReadLine();
            }
        }
    }
}

