name: Prebuild Docker image

on:
  push:
    branches:
    - master
    - cgranade/prebuild-docker # Temporarily enable on wrong branch to help test.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: microsoft
        # Container registry password
        password: ${{ secrets.GITHUB_TOKEN }}
        # Container registry server url
        login-server: https://docker.pkg.github.com/
    - name: Build and push Docker image
      run: |
        $ImageTag = "$([DateTime]::Now.Ticks)"
        $ImageName = "samples"
        $RepoName = "microsoft/quantum"
        
        $LocalTag = "${ImageName}:${ImageTag}"
        $RemoteTag = "docker.pkg.github.com/${RepoName}/${ImageName}:${ImageTag}"

        docker build . --tag $LocalTag
        docker tag $LocalTag $RemoteTag
        docker push $RemoteTag
      shell: pwsh
