name: Prebuild Docker image

on:
  push:
    branches:
    - master
    - cgranade/prebuild-docker # Temporarily enable on wrong branch to help test.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: microsoft
        # Container registry password
        password: ${{ secrets.GITHUB_TOKEN }}
        # Container registry server url
        login-server: https://docker.pkg.github.com/
    - name: Build and push Docker image
      run: |
        $Now = [DateTime]::Now;
        $ImageTag = "{0}{1:d2}{2:d2}.{3:d2}{4:d2}.{5:d2}{6:d4}" -f $Now.Year, $Now.Month, $Now.Day, $Now.Hour, $Now.Minute, $Now.Second, $Now.Millisecond
        $ImageName = "samples"
        $RepoName = "microsoft/quantum"
        
        $LocalTag = "${ImageName}:${ImageTag}"
        $RemoteRepo = "docker.pkg.github.com/${RepoName}/${ImageName}"

        docker build Build/images/samples --tag $LocalTag
        docker tag $LocalTag "${RemoteRepo}:${ImageTag}"
        docker push "${RemoteRepo}:${ImageTag}"
        docker tag $LocalTag "${RemoteRepo}:latest"
        docker push "${RemoteRepo}:latest"
      shell: pwsh
