name: Prebuild Docker image

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Azure login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.ACR_CREDENTIALS }}
    - name: Docker Login
      run: az acr login -n msquantum
    - name: Build and push Docker image
      run: |
        $Now = [DateTime]::Now;
        $ImageTag = "${{ github.sha }}"
        $RepoName = "public/quantum/samples"
        
        $LocalTag = "${RepoName}:${ImageTag}"
        $RemoteRepo = "${{ secrets.ACR_REGISTRY }}/${RepoName}"

        docker build Build/images/samples --tag $LocalTag
        docker tag $LocalTag "${RemoteRepo}:${ImageTag}"
        docker push "${RemoteRepo}:${ImageTag}"
        docker tag $LocalTag "${RemoteRepo}:latest"
        docker push "${RemoteRepo}:latest"
      shell: pwsh
